apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-ip-controller
  namespace: node-ip-controller
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: node-ip-controller
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: node-ip-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-ip-controller
subjects:
- kind: ServiceAccount
  name: node-ip-controller
  namespace: node-ip-controller
---
apiVersion: v1
kind: Namespace
metadata:
  name: node-ip-controller
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-ip-controller
  namespace: node-ip-controller
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: node-ip-controller
    spec:
      serviceAccountName: node-ip-controller
      containers:
      - name: node-ip-controller
        image: gcr.io/jonasbergler-com/node-ip-controller:v1.1
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /secret/dns
            name: secret-dns
            readOnly: true
        args: ["-v", "3"]
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /secret/dns/key.json
          - name: GCP_PROJECT_ID
            valueFrom:
              configMapKeyRef:
                name: config
                key: project
          - name: GCP_DNS_ZONE
            valueFrom:
              configMapKeyRef:
                name: config
                key: zone
          - name: GCP_DNS_DOMAIN
            valueFrom:
              configMapKeyRef:
                name: config
                key: domain
      volumes:
        - name: secret-dns
          secret:
            secretName: node-ip-dns-credentials
